### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/homebrew-goby#1]
Note that `brew install goby-lang/goby/goby` is needed, instead of `brew install goby`

**Comment by st0012** [comment]
I think just `brew install goby-lang/goby/` should work?

**Comment by hachi8833** [comment]
I thought the same, but my homebrew suggested as that.

**Comment by adlerhsieh** [comment]
Could you help try using just `brew install goby`?

**Comment by hachi8833** [comment]
Strange... works fine this time.
Close the issue.
